/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wsclock;

import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Evelyn
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        for (int i = 1; i < 33; i++) {
            cb_tmemoria1.addItem(i+"");
            //cb_tmemoria2.addItem(i+""); 
            double pot=Math.pow(2,i);
            int num =(int)pot;
            cb_pagina.addItem(num+"");
            cb_procesos.addItem(i+"");
            
        }
        table.setVisible(false);
        
        
        //Soy kevin colaborando con Evelin
        //Cambios en el codigo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_tmemoria1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_pagina = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cb_procesos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_tmemoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cb_tmemoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tmemoria1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb_tmemoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, 30));

        jLabel3.setBackground(new java.awt.Color(204, 109, 204));
        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Algoritmo de reemplazo de paginas WSClock");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel4.setText("memoria 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 10));

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel8.setText("Tamaño de la página");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel9.setText("Memoria fisica");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        getContentPane().add(cb_pagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel10.setText("Número de procesos ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        getContentPane().add(cb_procesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 80, 757, -1));

        txt_info.setColumns(20);
        txt_info.setRows(5);
        jScrollPane2.setViewportView(txt_info);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 240, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tmemoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tmemoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tmemoria1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ban=0;
        int t=Integer.parseInt( cb_procesos.getSelectedItem().toString());
        
        int procesos[]= new int [t];
        System.out.println(t);
        
        try{
            for ( int i = 0; i <t; i++) {
                procesos[i]=Integer.parseInt(JOptionPane.showInputDialog("Ingresa el tamaño del proceso: "+i));
                
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Solo números enteros");
            ban=1;
            
       }
        int marcos=0;
        if(ban==0){
           
       
           marcos=(Integer.parseInt(cb_tmemoria1.getSelectedItem().toString())/
                   Integer.parseInt(cb_pagina.getSelectedItem().toString()));
            System.out.println("marcos "+marcos);
        }
        for (int i = 1; i <=marcos; i++) {
            TableColumn tc=  new TableColumn();
            JTableHeader header = table.getTableHeader();
            
            table.addColumn(tc);
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_pagina;
    private javax.swing.JComboBox<String> cb_procesos;
    private javax.swing.JComboBox<String> cb_tmemoria1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txt_info;
    // End of variables declaration//GEN-END:variables
}
