/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wsclock;

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author por_s
 */
public class VtnTablaPaginas extends javax.swing.JFrame {

    /**
     * Creates new form VtnPrincipal
     */
    int pagina = 0;
    int numeroPaginasVirtual = 0;
    int numeroPaginasRAM = 0;
    long tamanioVirtual = Main.tamanioMemoriaVirtual * 1000000;
    long tamanioRAM = Main.tamanioMemoriaRAM * 1000;
    DefaultTableModel modeloRAM;
    public VtnTablaPaginas() {
        initComponents();
        this.setLocationRelativeTo(null);
        numeroPaginasVirtual = (int) (tamanioVirtual) / Main.tamanioPagina;
        numeroPaginasRAM = (int) (tamanioRAM) / Main.tamanioPagina;

       String[] columnas1 = {"Número de marco de pagina", "Direcciones de memoria","Bit R","Tiempo"};
        modeloRAM = new DefaultTableModel(null, columnas1);
        String[] filas1 = new String[2];

        
        
        
        for (int i = 0; i < numeroPaginasRAM; i++) {
            filas1[0] = i + "";
            filas1[1] = "";
            modeloRAM.addRow(filas1);
            modeloRAM.setValueAt(0, i, 2);
            //modeloRAM.setValueAt(0, i, 1);
        }
        jTable2.setModel(modeloRAM);
       
        DefaultTableModel modeloPaginacion;

        String[] columnas2 = new String[Main.numProcesos];
        String[] filas2 = new String[Main.numProcesos];

        for (int i = 0; i < Main.numProcesos; i++) {
            columnas2[i] = "Proceso " +Main.procesos[i].getNombre();
        }
        modeloPaginacion = new DefaultTableModel(null, columnas2);
        int a=0;
        int mayor = 0;
        for (int i = 0; i < Main.numProcesos; i++) {
            for (int j = 0; j < Main.procesos[i].paginas.length; j++) {
                a++;
              // modeloPaginacion.addRow(filas2);
            }
            if(a>mayor){
                mayor=a;
                a=0;
            }else{
                a=0;
                
            }
        }
        modeloPaginacion.setRowCount(mayor);
        for (int i = 0; i < Main.numProcesos; i++) {
            for (int j = 0; j < Main.procesos[i].paginas.length; j++) {
                modeloPaginacion.setValueAt(Main.procesos[i].paginas[j].getPagina(), j, i);
            }
        }

        jTable1.setModel(modeloPaginacion);

    }

    public void algoritmoSClock() {
        /*
    int posicion=0;
    boolean procesos;
    while(procesos){
     * if(R==1){
           + La página se usó en el tick actual. No es candidata
    
           R=false; //+ Se apaga el bit R
           posicion++;// Se adelanta la manecilla y se repite el algoritmo
           + Ver incisos a->b
    }else{
    if(tiempo>tiempoRango){
       - Indica que ya no pertenece al anillo y no es necesario protegerla. 
                - La nueva página se colocaría en el iguiente marco (Ver incisos c -> d)
    }else{
     + Si la edad > t y la página no ésta limpia
                - No se podrá quitar del anillo a menos de que se proteja
                - Sí existe una página limpia se pondrá en uso de inmediato
                - Para evitar cambios de procesos la manecilla del anillo se adelanta y el algoritmo continua su análisis
    }
    }
    
   if(manecilla){//Si la manecilla da la vuelta completa en el anillo, el valor sera true
           // Si se guarda al menos una escritura en el anillo
           // Seguirá dando vueltas la manecilla, hasta que algún proceso termine su escritura y la limpie
           // Si es limpiada se quitara del anillo automáticamente

    }else{
      
           // Si no se guarda ninguna escritura en el anillo
           //Indica que todas las páginas están dentro del anillo
           //Se utilizará cualquier marco de página que se encuentre vacío, sino es así se guardara en disco
    }
         */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boton2 = new Boton.Boton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        boton3 = new Boton.Boton();
        jLabel5 = new javax.swing.JLabel();
        jTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WSClock");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Algoritmo de reemplazo de paginas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, 1010, -1));

        boton2.setText("Ejecutar algoritmo");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tabla de páginas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 159, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 720, 410));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Número de marco", "Memoria virtual", "Bit R", "Bit M", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 167, 520, 390));

        jLabel4.setText("Tiempo virtual:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 90, 20));

        boton3.setText("Regresar");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        jLabel5.setText("Memoria virtual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 230, -1));

        jTiempo.setBackground(new java.awt.Color(204, 204, 204));
        jTiempo.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTiempo.setOpaque(true);
        jPanel1.add(jTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1309, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        


        hilo = new Hilo(jTiempo, jTable2,modeloRAM );
        if (corriendo == false) {
            estado = true;
            corriendo = true;
             hilo();
             
        }else{
            System.out.println("sigue corriendo");
        }
       
        
       // algoritmo();
        boton2.setEnabled(false);
        
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        if (hilo!=null) {
           if (hilo.isAlive()) {
            hilo.stop();
        } 
        }
        
        
        new VtnTamanioProcesos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton3ActionPerformed
 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Boton.Boton boton2;
    private Boton.Boton boton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    public javax.swing.JLabel jTiempo;
    // End of variables declaration//GEN-END:variables
 int segundo = 0;

    boolean estado = true;
    boolean corriendo = false;
    Hilo hilo;

    private void hilo() {

        if (estado == true) {

            hilo.start();
        } else {
            hilo.stop();
        }
    }
}
